#!/usr/bin/env bash

set -o errexit
set -o pipefail

# shellcheck disable=SC2155
export PROJECT_DIR=$(git rev-parse --show-toplevel)

# shellcheck disable=SC2155
export SOPS_AGE_KEY_FILE=~/.config/sops/age/keys.txt

# shellcheck disable=SC1091
source "${PROJECT_DIR}/.config.env"


main() {

generate_ansible_router_secrets
generate_ansible_host_secrets

}

generate_ansible_router_secrets() {
    local node_id=${BOOTSTRAP_ROUTER_HOST_ADDR}
    local node_username=${BOOTSTRAP_ROUTER_SSH_USERNAME}
    local node_password=${BOOTSTRAP_ROUTER_SUDO_PASSWORD}
    local node_hostname=${BOOTSTRAP_ROUTER_HOSTNAME}
    local node_public_domain=${SECRET_PUBLIC_DOMAIN}
    local node_private_domain=${SECRET_PRIVATE_DOMAIN}
    {
        printf "kind: Secret\n"
        printf "ansible_user: %s\n" "${node_username}"
        printf "ansible_become_pass: %s\n" "${node_password}"
        printf "SECRET_PUBLIC_DOMAIN: %s\n" "${node_public_domain}"
        printf "SECRET_PRIVATE_DOMAIN: %s\n" "${node_private_domain}"
    } > "${PROJECT_DIR}/ansible/router/inventory/host_vars/${node_hostname}.sops.yml"
    sops --encrypt --in-place "${PROJECT_DIR}/ansible/router/inventory/host_vars/${node_hostname}.sops.yml"
}

generate_ansible_host_secrets() {
    #local node_count=0
    local node_id=0
    local node_username=${BOOTSTRAP_ANSIBLE_SSH_USERNAME}
    local node_password=${BOOTSTRAP_ANSIBLE_SUDO_PASSWORD}
    local node_control=
    local node_hostname=
    local test_var
    for var in "${!BOOTSTRAP_ANSIBLE_HOST_ADDR_@}"; do
        test_var="BOOTSTRAP_ANSIBLE_HOSTNAME_${!var}"
        node_control="${!test_var}"
        test_var="BOOTSTRAP_CONTROL_NODE_${!var}"
        node_hostname="${!test_var}"
        {
        printf "kind: Secret\n"
        printf "ansible_user: %s\n" "${node_username}"
        printf "ansible_become_pass: %s\n" "${node_password}"                
        } > "${PROJECT_DIR}/ansible/kubernetes/inventory/host_vars/${!var}.sops.yml"
            sops --encrypt --in-place "${PROJECT_DIR}/ansible/kubernetes/inventory/host_vars/${!var}.sops.yml"
        node_id=$((node_id+1))
    done
}

main