---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: traefik-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/traefik/traefik-helm-chart
  ref:
    # renovate: registryUrl=https://helm.traefik.io/traefik chart=traefik
    tag: v18.3.0

