#yamllint diable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: external-dns
  namespace: default
stringData:
  email: ${BOOTSTRAP_CLOUDFLARE_EMAIL}
  api-key: ${BOOTSTRAP_CLOUDFLARE_APIKEY}