---
router:
  hosts:
    opnsense:
      ansible_host: 10.28.1.1
      ansible_user: brian
  vars:
    ansible_shell_executable: /usr/local/bin/bash
    ansible_python_interpreter: /usr/local/bin/python3
    ansible_perl_interpreter: /usr/local/bin/perl