---
kubernetes:
  children:
    master:
      hosts:
        k8s0:
          ansible_host: 10.28.28.40
        k8s1:
          ansible_host: 10.28.28.41
        k8s2:
          ansible_host: 10.28.28.42
      vars:
        ansible_user: root
        ansible_ssh_port: 22
    worker:
      hosts:
        k8s3:
          ansible_host: 10.28.28.43
          rook_devices:
            - /dev/nvme0n1
        k8s4:
          ansible_host: 10.28.28.44
          rook_devices:
            - /dev/nvme0n1
        k8s5:
          ansible_host: 10.28.28.45
          rook_devices:
            - /dev/nvme0n1
      vars:
        ansible_user: root