---
timezone: "America/Chicago"

public_ssh_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDLBWNW9rNJXTC+Y9uVyeM6dHGKzc6X625cG2ZFl/dqaJ5sSK/ZbSt9CmGmOTfPZtP7uDLgXG80yqY6RYan57act+w1NqMO7cXcXp5GyU+WU8pHb5oxr8OCNOgwvT77eFpc0+AvwaWwUpJfiwjU5rNjtsh2Z/edbhADJ/Z7K0dSdFe3ttzWvY2+9XWQbDCd1qk20bdD8yNmrjTNIq/djJs0Vor/QonMNw9ldCnnmWATbuu1NMnfe2w612MYOZWC/F2kmxtL4iRylK/r9q9X5vucIr/wrtru2+4P0rfzwzc4ABwBdGQsy8+1wsDpyecMDB/GMGTdbH1PkrORSdVuX7PL brian@MacMini"
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDYpBivxjEFzbXwFCIGAdJFicPn+aGQLhk64GFCDno/FIRN49Y20Cv1mBivqSew9NnOKHT7Y0J/DxUjjIWpuKRt+tedBejDU1FpfdATVQ2NBwV+775MiZlCxGAKXyP0oef9ha+59yrtfFpzkKaq+yJax53/YNSkxnJ2MiVzxU08pLa8iwRHecP5vDcpVtwDFlCK8ljvE8vFTHBzk8qCGYkMpoKMdnGAyyu03TwLBkgDtYCi1WPU3FcfTm1qZuJUS2UIvaNw7k/g9jGnSZz66xgKBW12a0GXh2i4fpcGZ/Ofyjrs3h7Jm6k0MyEikEQ+HaB95uve6lHXIn73brVNLB2f PanicKey@Nova"
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCh+EjcuIRrFijfpbcdCtjTGXb2eLtAws0sdrBHRxFnBTPdx2dseOn6MVLW2uBA6kWd1iqDzGkQv/nu+fQA5z0Ub77YKIYrRGN6V5bt4YsdjHIRAehlB/flHjza8PS0O/UhJojXRa1HTYWtEE1EX/bmQxdH6crR/AwNFVtD5btNdk+GrtWvIrf17UHk3yswxefHE/cHYYb41YKw+uAZhRbDhDeMN0pPLs6vrFipDzm7heDxpGuDTaN/4DlkQI/PMjYbV886uQI3K8UKsAhnuSji0TKn7u2mWWLqvicx1HlRFW3FYDStgbFhYCD03pHenWNvD2/VLLOrnSHSmzswYYKMyHcfGQxZS81AA2Gy5wD5jxfHQ/IkL88dxoQn75ChnlSn4JHaIT/paJ5pT3sAQjdNzn1jdTaMLZwRbJiJhIF9ZROx5PZAN24T25UTRwMQIS5mQ0Mu4nCNEHyiXYm4YmcoCeql0lsKdjN2hqRm0LSdLNHwt3nTm5f6NPr0Kb8RhNUU5wUrvxfZhqYubFuEdndCIll6aKk9UyEAbSNtDeQxsuTsqrTrqiQ/p009kU8Mzz+mppBZP8rM3QB6s35LQ7r+IepVEHZP7OeGRLnj/cjz3GcTZLq1wwtrxHNYY2YbcWlbqY+kNo80/F0OqmHCB4tUpn9r/ic/fQZYiWi+DGaS9w== brian@desktop"
# TODO(ansible): Some packages might be required for newer Intel CPU generations
# https://ask.fedoraproject.org/t/intel-graphics-best-practices-and-settings-for-hardware-acceleration/21119
packages:
  - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
  - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
  - dnf-automatic
  - dnf-plugin-system-upgrade
  - dnf-utils
  #- fish
  #- hdparm
  - htop
  - ipvsadm
  - neovim
  - python3-libselinux
  - socat